apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: myapp-routerules-100c
spec:
  destination:
    name: myapp-GKE_1-lb
    domain: svc.cluster.local
  route:
  - labels:
      stack: canary
    weight: 100
